name 'docs-builder'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures docs-builder'
long_description 'Installs/Configures docs-builder'
version '0.1.5'

depends 'aws'
depends 'fancy_execute'
