name 'docs-builder'
maintainer 'Chef Docs Team'
maintainer_email 'docs@chef.io'
license 'Apache-2.0'
description 'Installs/Configures docs-builder'
long_description 'Installs/Configures docs-builder'
version '0.3.3'
