[getjson]
dir = ":resourceDir/_get"
maxAge = -1
[getresource]
dir = ":resourceDir/_get"
maxAge = -1
[getcsv]
dir = ":resourceDir/_get"
maxAge = -1
[images]
dir = ":resourceDir/_gen"
maxAge = -1
[assets]
dir = ":resourceDir/_gen"
maxAge = -1
