#!/bin/bash

unset SSH_AUTH_SOCK
ssh -o CheckHostIP=no \
    -o IdentitiesOnly=yes \
    -o LogLevel=INFO \
    -o StrictHostKeyChecking=no \
    -o PasswordAuthentication=no \
    -o UserKnownHostsFile=/root/.ssh/known_hosts \
    -o IdentityFile=/root/.ssh/id_rsa \
    -l builder \
    $*
