name             'build-cookbook'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures build-cookbook'
long_description 'Installs/Configures build-cookbook'
version          '0.1.1'

depends 'cia_infra'
depends 'cia_delivery'
depends 'fancy_execute'
depends 'delivery-truck'
