name             'build-cookbook'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures build-cookbook'
long_description 'Installs/Configures build-cookbook'
version          '0.1.1'

depends 'delivery-truck'
depends 'chef_handler'
depends 'chef-sugar'
depends 'route53'
depends 'fastly'
depends 'nodejs'
depends 'chef_slack'
depends 'build-essential'
depends 'fancy_execute'
