name             'build-cookbook'
maintainer       'Chef Docs Team'
maintainer_email 'docs@chef.io'
license          'Apache 2.0'
description      'Installs/Configures build-cookbook'
long_description 'Installs/Configures build-cookbook'
version          '0.1.5'

depends 'delivery-truck'
depends 'chef_handler'
depends 'chef-sugar'
depends 'route53'
depends 'fastly'
depends 'nodejs'
depends 'build-essential'
depends 'fancy_execute'
