#!/bin/bash

#
# This script checks all restructuredText topics in master dir
# for adherence to Chef docs conventions. These are:
#
# - H1 headings have overline and underline adornment using the "=" character.
#
# - Section headings other H1 use underline adornment only.
#
# - H2 headings use the "=" character for their underline adornment.
#
# - H3 headings use the "-" character for their underline adornment.
#
# - H4 headings use the "+" character for their underline adornment.
#
# - H5 headings use the "^" character for their underline adornment.
#
# - Nesting is consecutve; for example, H3 can follow H2 but not H1
#
# To do: take include files into account. (Normally, include files
# do not include sections.)


RST_SOURCE_DIR="../../../../chef_master/source"
ls -1 $RST_SOURCE_DIR/*.rst | ruby ./checkheads.rb
