 - workload: pull_request_merged:chef/chef-web-docs:main:*
    actions:
      - bash:.expeditor/update_docs_lints.sh:
          only_if_modified:
            - .markdownlint.yaml
            # - .vale.ini
            # - cspell.json
            # - .github/workflows/*
            # - .github/labler.yml

