[module]

  [[module.imports]]
    disable = false
    ignoreConfig = false
    path = "github.com/chef/chef-workstation"

  [[module.imports.mounts]]
    source = "www/content"
    target = "content"

  [[module.imports.mounts]]
    source = "www/static"
    target = "static"
