#!/usr/bin/env ruby

# This script checks if the 'edit on GitHub' link is present at the top of the source file.

GHLINKREGEX = /(`\[edit on GitHub\] <.*>`_)/
@errors = []

# Do regex for `[edit on GitHub] <https://github.com/chef/chef-web-docs/blob/master/chef_master/source/filename.rst>`__
def check_gh_link(file)

  File.foreach(file).with_index do |line, line_num|

    # If the link is present, return nil so the next file can be parsed.
    return nil if line.match(GHLINKREGEX)

    # Return an error message if the 'edit on GitHub' link is not present by line number 7.
    if line_num == 7
      @errors << "No edit link found in #{file}"
      break
    end
  end
end

# Search through all source files in the current directory. It's assumed that the cwd is chef_master/source.
Dir.glob("*.rst") do |result|
  check_gh_link(result)
end

@errors.each { |error| $stderr.puts(error) }
exit(!@errors.empty? ? 1 : 0)
